const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_FAILED = 'SIGNUP_FAILED';
const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
const LOGIN_FAILED = ' LOGIN_FAILED';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGOUT_FAILED = ' LOGIN_FAILED';
const LOGOUT_SUCCESS = 'LOGIN_SUCCESS';
const PROFILE_REQUEST = 'PROFILE_REQUEST';
const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
const PROFILE_FAILED = 'PROFILE_FAILED';
const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
const UPDATE_FAILED = 'UPDATE_FAILED';
const SINGLE_REQUEST = 'SINGLE_REQUEST';
const SINGLE_SUCCESS = 'SINGLE_SUCCESS';
const SINGLE_FAILED = 'SINGLE_FAILED';

export {
  SIGNUP_FAILED,
  SIGNUP_REQUEST,
  SIGNUP_SUCCESS,
  PROFILE_FAILED,
  UPDATE_FAILED,
  LOGIN_FAILED,
  LOGIN_SUCCESS,
  PROFILE_SUCCESS,
  PROFILE_REQUEST,
  UPDATE_SUCCESS,
  LOGOUT_SUCCESS,
  LOGOUT_FAILED,
  SINGLE_REQUEST,
  SINGLE_SUCCESS,
  SINGLE_FAILED,
};
